### ISSUE TITLE
Userlooks: Ben S, Ben H (or other writer/comm), IaD (Vicky/Becky/Nathan?), Sam?

### ISSUE THREAD

**Issue by FrancescaV** [ideo/avocado-allegory#15]

**Comment by gambingo** [comment]
List of people:
- [x] A writer – Ben, Ben, Christina
- [x] IxD – Nathan, Vicky, or ~Becky~
- [x] DS Director – Bo or Dean
- [ ] Creative Software – ~YC~ or Sam

**Comment by gambingo** [comment]
I've scheduled calls with:
- [x] Christina
- [x] Vicky
- [ ] ~Becky~
- [x] Bo
- [ ] Ben S
- [ ] Sam
